name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - seaborn=0.11.1
  - pip=20.3.3
  - scikit-learn=0.24.1
  - jupyterlab=3.0.12
  - mlflow=1.14.1
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.16.0
