name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow==1.14.1
  - hydra-core=1.3.2
  - ipython=7.21.0
  - notebook=6.2.0
  - matplotlib=3.8.2
  - cookiecutter=1.7.2
  - pandas=2.1.3
  - jupyterlab=3.0.10
  - pip=23.3.1
  - pip:
      - wandb==0.16.0